In [1]:
import numpy as np
import pandas as pd
import json
import ast
import itertools

In [103]:
track_data=pd.read_json(r"C:\\Users\desai\\Downloads\\20200912-NSH-ATL_886b2a47-3249-4e95-8200-f7cdd8fbbf46_SecondSpectrum_Data.jsonl",lines=True)

In [104]:
track_data.head(10)

,period,frameIdx,gameClock,wallClock,homePlayers,awayPlayers,ball,live,lastTouch
0,1,0,0.00,1599957484770,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-0.06, 0.04, 0.22], 'speed': 17.17}",False,home
1,1,1,0.04,1599957484810,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-0.75, 0.04, 0.29], 'speed': 17.0}",True,away
2,1,2,0.08,1599957484850,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-1.49, 0.02, 0.34], 'speed': 16.83}",True,away
3,1,3,0.12,1599957484890,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-2.21, 0.02, 0.35000000000000003], 's...",True,away
4,1,4,0.16,1599957484930,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-2.91, 0.02, 0.34], 'speed': 16.46}",True,away
5,1,5,0.20,1599957484970,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-3.61, 0.01, 0.34], 'speed': 16.28}",True,away
6,1,6,0.24,1599957485010,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-4.31, 0.01, 0.33], 'speed': 16.11}",True,away
7,1,7,0.28,1599957485050,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-4.97, -0.0, 0.31], 'speed': 15.93}",True,away
8,1,8,0.32,1599957485090,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-5.63, -0.01, 0.30000000000000004], '...",True,away
9,1,9,0.36,1599957485130,"[{'playerId': '220753', 'number': 29, 'xyz': [...","[{'playerId': '41705', 'number': 1, 'xyz': [-4...","{'xyz': [-6.26, -0.01, 0.29], 'speed': 15.56}",True,away

In [7]:
track_data.to_csv("tracking_data.csv")

In [168]:
data_track=pd.read_csv("tracking_data.csv")

In [169]:
#Convert the strings in those columns to lists because latter we will be flattening them to separate columns
data_track["homePlayers"] = data_track["homePlayers"].apply(lambda x: ast.literal_eval(x))
data_track["awayPlayers"] = data_track["awayPlayers"].apply(lambda x: ast.literal_eval(x))
data_track["ball"] = data_track["ball"].apply(lambda x: ast.literal_eval(x))

In [170]:
home_pl_df = pd.DataFrame(list(itertools.chain(*data_track["homePlayers"].values.tolist())))
away_pl_df = pd.DataFrame(list(itertools.chain(*data_track["awayPlayers"].values.tolist())))
ball_df=data_track['ball'].apply(pd.Series)

In [171]:
home_pl_df.columns = ['playerIdHome','numberHome','xyzHome','speedHome']
away_pl_df.columns = ['playerIdAway','numberAway','xyzAway','speedAway']
ball_df.columns=['ball_xyz','ball_speed']

In [172]:
data_track = data_track.drop(['homePlayers','awayPlayers','ball'],axis=1)

In [173]:
players = pd.concat([home_pl_df,away_pl_df],axis=1)

In [174]:
ball_players=pd.concat([players,ball_df],axis=1)

In [175]:
data_track_2 = pd.concat([data_track,ball_players],axis=1)

In [176]:
data_track_2.head(10)

,Unnamed: 0,period,frameIdx,gameClock,wallClock,live,lastTouch,playerIdHome,numberHome,xyzHome,speedHome,playerIdAway,numberAway,xyzAway,speedAway,ball_xyz,ball_speed
0,0.0,1.0,0.0,0.00,1.599957e+12,False,home,220753,29,"[0.49, -19.84, 0.0]",0.0,41705,1,"[-47.28, -0.13, 0.0]",0.0,"[-0.06, 0.04, 0.22]",17.17
1,1.0,1.0,1.0,0.04,1.599957e+12,True,away,41626,6,"[7.6, 4.82, 0.0]",0.0,221678,9,"[-9.89, 7.66, 0.0]",0.0,"[-0.75, 0.04, 0.29]",17.00
2,2.0,1.0,2.0,0.08,1.599957e+12,True,away,177928,2,"[15.36, -23.38, 0.0]",0.0,152253,14,"[0.46, -0.24, 0.0]",0.0,"[-1.49, 0.02, 0.34]",16.83
3,3.0,1.0,3.0,0.12,1.599957e+12,True,away,151933,25,"[21.1, 6.57, 0.0]",0.0,426771,21,"[-7.7, 32.85, 0.0]",0.0,"[-2.21, 0.02, 0.35000000000000003]",16.64
4,4.0,1.0,4.0,0.16,1.599957e+12,True,away,479525,12,"[14.99, 20.68, 0.0]",0.0,41551,18,"[-15.13, 0.43, 0.0]",0.0,"[-2.91, 0.02, 0.34]",16.46
5,5.0,1.0,5.0,0.20,1.599957e+12,True,away,99117,20,"[8.16, -4.26, 0.0]",0.0,158536,4,"[-19.33, 16.2, 0.0]",0.0,"[-3.61, 0.01, 0.34]",16.28
6,6.0,1.0,6.0,0.24,1.599957e+12,True,away,213213,4,"[21.39, -9.08, 0.0]",0.0,178386,11,"[-0.28, -28.53, 0.0]",0.0,"[-4.31, 0.01, 0.33]",16.11
7,7.0,1.0,7.0,0.28,1.599957e+12,True,away,95309,1,"[46.92, -0.01, 0.0]",0.0,442345,28,"[-1.52, -9.6, 0.0]",0.0,"[-4.97, -0.0, 0.31]",15.93
8,8.0,1.0,8.0,0.32,1.599957e+12,True,away,202376,9,"[0.32, 9.91, 0.0]",0.0,231969,8,"[-0.16, 21.37, 0.0]",0.0,"[-5.63, -0.01, 0.30000000000000004]",15.74
9,9.0,1.0,9.0,0.36,1.599957e+12,True,away,202195,7,"[0.68, 22.24, 0.0]",0.0,241500,12,"[-22.06, -8.31, 0.0]",0.0,"[-6.26, -0.01, 0.29]",15.56

In [177]:
data_track_2.to_csv("tracking_data_fin.csv")

In [183]:
ball_coords=pd.DataFrame(data_track_2['ball_xyz'].apply(pd.Series),columns=['ball_x','ball_y','ball_z'])

In [184]:
Home_coords=pd.DataFrame(data_track_2['xyzHome'].apply(pd.Series),columns=['Home_x','Home_y','Home_z'])

In [185]:
Away_coords=pd.DataFrame(data_track_2['xyzAway'].apply(pd.Series),columns=['Away_x','Away_y','Away_z'])

In [186]:
data_track_bh = pd.concat([ball_coords,Home_coords],axis=1)

In [187]:
data_track_bha=pd.concat([data_track_bh,Away_coords],axis=1)

In [188]:
data_track_fin=pd.concat([data_track_2,data_track_bha],axis=1)

In [189]:
data_track_fin.head(10)

,Unnamed: 0,period,frameIdx,gameClock,wallClock,live,lastTouch,playerIdHome,numberHome,xyzHome,...,ball_speed,ball_x,ball_y,ball_z,Home_x,Home_y,Home_z,Away_x,Away_y,Away_z
0,0.0,1.0,0.0,0.00,1.599957e+12,False,home,220753,29,"[0.49, -19.84, 0.0]",...,17.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,1.0,0.04,1.599957e+12,True,away,41626,6,"[7.6, 4.82, 0.0]",...,17.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,1.0,2.0,0.08,1.599957e+12,True,away,177928,2,"[15.36, -23.38, 0.0]",...,16.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,1.0,3.0,0.12,1.599957e+12,True,away,151933,25,"[21.1, 6.57, 0.0]",...,16.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,1.0,4.0,0.16,1.599957e+12,True,away,479525,12,"[14.99, 20.68, 0.0]",...,16.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5.0,1.0,5.0,0.20,1.599957e+12,True,away,99117,20,"[8.16, -4.26, 0.0]",...,16.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,1.0,6.0,0.24,1.599957e+12,True,away,213213,4,"[21.39, -9.08, 0.0]",...,16.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.0,1.0,7.0,0.28,1.599957e+12,True,away,95309,1,"[46.92, -0.01, 0.0]",...,15.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8.0,1.0,8.0,0.32,1.599957e+12,True,away,202376,9,"[0.32, 9.91, 0.0]",...,15.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9.0,1.0,9.0,0.36,1.599957e+12,True,away,202195,7,"[0.68, 22.24, 0.0]",...,15.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
data_track_fin.to_csv("tracking_data_final.csv")

In [ ]:
data_track_fin.drop(['ball_xyz','xyzHome','xyzAway'],axis=1,inplace=True)

In [191]:
ball_coords

         ball_x  ball_y  ball_z
0           NaN     NaN     NaN
1           NaN     NaN     NaN
2           NaN     NaN     NaN
3           NaN     NaN     NaN
4           NaN     NaN     NaN
...         ...     ...     ...
1553283     NaN     NaN     NaN
1553284     NaN     NaN     NaN
1553285     NaN     NaN     NaN
1553286     NaN     NaN     NaN
1553287     NaN     NaN     NaN

[1553288 rows x 3 columns]

In [194]:
 pd.DataFrame(data_track_2['ball_xyz'].head(10).str.split().values.tolist())

    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN
8 NaN
9 NaN

In [195]:
data_track_2['ball_xyz'].head(10)

0                    [-0.06, 0.04, 0.22]
1                    [-0.75, 0.04, 0.29]
2                    [-1.49, 0.02, 0.34]
3     [-2.21, 0.02, 0.35000000000000003]
4                    [-2.91, 0.02, 0.34]
5                    [-3.61, 0.01, 0.34]
6                    [-4.31, 0.01, 0.33]
7                    [-4.97, -0.0, 0.31]
8    [-5.63, -0.01, 0.30000000000000004]
9                   [-6.26, -0.01, 0.29]
Name: ball_xyz, dtype: object

In [2]:
df=pd.read_excel("tracking_data_fin.xlsx")

In [4]:
df_home=df[df["lastTouch"]=='home'] ## obs with possession with the home team

In [5]:
df_away=df[df["lastTouch"]=='away'] ## obs with possession with the away team

In [8]:
df_home

,period,frameIdx,gameClock,wallClock,live,lastTouch,playerIdHome,numberHome,Home_x,Home_y,...,ball_x,ball_y,ball_z,ball_speed,Ball_home_x_squared,Ball_home_y_squared,Ball_home_euclidean,Ball_away_x_squared,Ball_away_y_squared,Ball_away_euclidean
0,1.0,0.0,0.00,1.599957e+12,0.0,home,220753,29,0.49,-19.84,...,-0.06,0.04,0.22,17.17,0.3025,395.2144,19.887607,2229.7284,0.0289,47.220306
397,1.0,397.0,15.88,1.599958e+12,1.0,home,41626,6,5.81,6.17,...,-12.38,21.42,0.50,4.71,330.8761,232.5625,23.736862,20.0704,144.0000,12.808997
398,1.0,398.0,15.92,1.599958e+12,1.0,home,177928,2,13.63,-23.41,...,-12.79,21.42,0.60,3.35,698.0164,2009.7289,52.036000,254.0836,475.6761,27.014065
399,1.0,399.0,15.96,1.599958e+12,1.0,home,151933,25,19.54,6.60,...,-13.12,21.53,0.73,2.73,1066.6756,222.9049,35.910730,42.6409,128.1424,13.068408
400,1.0,400.0,16.00,1.599958e+12,1.0,home,479525,12,13.59,21.14,...,-13.52,21.50,0.83,3.18,734.9521,0.1296,27.112390,4.4521,472.1929,21.832201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141163,2.0,141163.0,2942.80,1.599964e+12,0.0,home,220753,29,11.95,-11.27,...,41.85,-30.93,-0.01,0.03,894.0100,386.5156,35.784432,5158.1124,1221.5025,79.872492
141164,2.0,141164.0,2942.84,1.599964e+12,0.0,home,41626,6,11.64,-0.55,...,41.85,-30.93,-0.01,0.04,912.6441,922.9444,42.843769,1106.2276,1974.9136,55.508028
141165,2.0,141165.0,2942.88,1.599964e+12,0.0,home,177928,2,24.24,-13.25,...,41.85,-30.93,-0.01,0.04,310.1121,312.5824,24.953847,279.8929,2044.8484,48.215571
141166,2.0,141166.0,2942.92,1.599964e+12,0.0,home,151933,25,25.24,11.18,...,41.86,-30.93,-0.01,0.05,276.2244,1773.2521,45.271144,707.5600,4174.4521,69.871397
141167,2.0,141167.0,2942.96,1.599964e+12,0.0,home,479525,12,24.75,21.67,...,41.86,-30.93,-0.01,0.05,292.7521,2766.7600,55.312857,1557.8809,916.8784,49.746953

In [10]:
press_home_possess=df_home[df_home["Ball_away_euclidean"]<=5]

In [11]:
press_away_possess=df_home[df_home["Ball_home_euclidean"]<=5]

In [12]:
df_home.to_csv("home_posses.csv")

In [13]:
df_away.to_csv("away_posses.csv")

In [14]:
press_home_possess

,period,frameIdx,gameClock,wallClock,live,lastTouch,playerIdHome,numberHome,Home_x,Home_y,...,ball_x,ball_y,ball_z,ball_speed,Ball_home_x_squared,Ball_home_y_squared,Ball_home_euclidean,Ball_away_x_squared,Ball_away_y_squared,Ball_away_euclidean
1397,1.0,1397.0,55.88,1.599958e+12,1.0,home,220753,29,-15.68,-25.94,...,-50.41,-0.45,1.00,7.90,1206.1729,649.7401,43.080309,9.1204,0.0729,3.032046
4234,1.0,4234.0,169.36,1.599958e+12,1.0,home,119089,10,-33.39,9.74,...,-19.18,-21.20,3.93,8.52,201.9241,957.2836,34.047139,0.0225,0.0004,0.151327
4245,1.0,4245.0,169.80,1.599958e+12,1.0,home,119089,10,-33.21,9.83,...,-22.80,-22.49,4.44,8.72,108.3681,1044.5824,33.955125,11.9716,2.0736,3.747693
7404,1.0,7404.0,296.16,1.599958e+12,1.0,home,41626,6,-24.86,14.98,...,-34.31,17.86,0.05,5.26,89.3025,8.2944,9.879114,14.9769,5.9536,4.574986
7415,1.0,7415.0,296.60,1.599958e+12,1.0,home,41626,6,-24.91,14.94,...,-37.17,16.62,0.16,7.60,150.3076,2.8224,12.374571,1.0404,1.3456,1.544668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141002,2.0,141002.0,2936.36,1.599964e+12,0.0,home,479525,12,23.70,20.42,...,NaN,NaN,NaN,0.00,561.6900,416.9764,31.283644,5.8081,7.3441,3.626596
141013,2.0,141013.0,2936.80,1.599964e+12,0.0,home,479525,12,23.77,20.51,...,NaN,NaN,NaN,0.00,565.0129,420.6601,31.395430,5.7600,6.6049,3.516376
141024,2.0,141024.0,2937.24,1.599964e+12,0.0,home,479525,12,23.82,20.59,...,NaN,NaN,NaN,0.00,567.3924,423.9481,31.485560,5.7121,5.9049,3.408372
141035,2.0,141035.0,2937.68,1.599964e+12,0.0,home,479525,12,23.88,20.68,...,NaN,NaN,NaN,0.00,570.2544,427.6624,31.589821,5.6644,5.2441,3.302802
141046,2.0,141046.0,2938.12,1.599964e+12,0.0,home,479525,12,23.94,20.76,...,NaN,NaN,NaN,0.00,573.1236,430.9776,31.687556,5.6169,4.6225,3.199906

In [17]:
f = open("C:\\Users\desai\\Downloads\\20200912-NSH-ATL_886b2a47-3249-4e95-8200-f7cdd8fbbf46_SecondSpectrum_Metadata.json")

In [18]:
metadata=json.load(f)

In [23]:
metadata

{'description': 'NSH - ATL : 2020-9-13',
 'startTime': 1599957484770,
 'year': 2020,
 'month': 9,
 'day': 13,
 'pitchLength': 105.7656021118164,
 'pitchWidth': 68.58000183105469,
 'fps': 25.0,
 'periods': [{'number': 1,
   'startFrameClock': 1599957484770,
   'endFrameClock': 1599960188450,
   'startFrameIdx': 0,
   'endFrameIdx': 67592,
   'homeAttPositive': False},
  {'number': 2,
   'startFrameClock': 1599961165490,
   'endFrameClock': 1599964110050,
   'startFrameIdx': 67593,
   'endFrameIdx': 141207,
   'homeAttPositive': True}],
 'homePlayers': [{'name': 'A. Danladi',
   'number': 7,
   'position': 'RW',
   'ssiId': '0811e82b-9274-4a21-8071-83647b4c4bc9',
   'optaId': '202195',
   'optaUuid': '1wfz5avhq6h41axvxggwa6vvt'},
  {'name': 'A. Johnston',
   'number': 12,
   'position': 'RB',
   'ssiId': '0c0f65ce-18f4-4f84-862c-29b5d1f9b144',
   'optaId': '479525',
   'optaUuid': 'epwfc94g7m7ed1nbt9wbgo6ei'},
  {'name': 'T. Washington',
   'number': 23,
   'position': 'SUB',
   'ssiId': '12438fbe-f7ac-4aa4-8adb-983bc076fccd',
   'optaId': '221255',
   'optaUuid': '1acejqkxxruued7otxg7wcell'},
  {'name': 'A. Godoy',
   'number': 20,
   'position': 'LDM',
   'ssiId': '16d1cf1a-1f2c-4802-9616-ce52e351b4dd',
   'optaId': '99117',
   'optaUuid': '4ajhe29nxseyo6wqg3hjdghcl'},
  {'name': 'J. Willis',
   'number': 1,
   'position': 'GK',
   'ssiId': '1fef9c19-5e91-4e30-a0f5-a92eeca0b927',
   'optaId': '95309',
   'optaUuid': '241n038j8171d06j7y97ug4id'},
  {'name': 'D. Romney',
   'number': 4,
   'position': 'LCB',
   'ssiId': '2d4e6f77-b4c2-4a77-a903-9fa4b8bff949',
   'optaId': '213213',
   'optaUuid': '49hih9ka1cljgkihamec6b17t'},
  {'name': 'A. Winn',
   'number': 19,
   'position': 'SUB',
   'ssiId': '39f7d114-a799-472e-ac0b-0151d021df4b',
   'optaId': '442474',
   'optaUuid': 'bpkip96s2p3zhx2ew2fl2hwid'},
  {'name': 'W. Zimmerman',
   'number': 25,
   'position': 'RCB',
   'ssiId': '5998bc4a-77ec-49cc-8736-184bd70d9d6d',
   'optaId': '151933',
   'optaUuid': 'eooivgc2bc7bdbl1gq784ehn9'},
  {'name': 'J. Maher',
   'number': 18,
   'position': 'SUB',
   'ssiId': '68f5a75d-d6d2-41e8-83a4-bc9550716165',
   'optaId': '421186',
   'optaUuid': 'a4vlno5u5qsph97hfa71ku8yx'},
  {'name': 'A. Muyl',
   'number': 29,
   'position': 'LW',
   'ssiId': '779410fe-983c-4e0c-8216-c19b6771878d',
   'optaId': '220753',
   'optaUuid': '64vrzsvixp5cvq9b7ol723zkl'},
  {'name': 'D. Badji',
   'number': 9,
   'position': 'ST',
   'ssiId': '94c557db-0e5a-422f-ba6a-3ce97322b9f6',
   'optaId': '202376',
   'optaUuid': 'dhwk7axf00z4pe7crgp3ge8yx'},
  {'name': 'B. Beckeles',
   'number': 55,
   'position': 'SUB',
   'ssiId': 'a5eba55b-b6ac-471b-9220-4125a541d7f8',
   'optaId': '99336',
   'optaUuid': 'akvnlaszzemsj14oa62n39c5x'},
  {'name': 'J. Anibaba',
   'number': 3,
   'position': 'SUB',
   'ssiId': 'a654658a-2189-4a42-8fa3-1c4183eee25c',
   'optaId': '95228',
   'optaUuid': 'cfucb8do9rkxdk9381cinmqd'},
  {'name': 'H. Mukhtar',
   'number': 10,
   'position': 'CAM',
   'ssiId': 'ad87de3c-9c65-4623-8a3d-76831d56b038',
   'optaId': '119089',
   'optaUuid': '94jvlb3r2cq9ryxco4fmkbmxh'},
  {'name': 'D. Rios',
   'number': 14,
   'position': 'SUB',
   'ssiId': 'c2951a4d-c534-4b1a-8b3a-b7a078fbf9d8',
   'optaId': '204328',
   'optaUuid': '7su9vrjsmo84ae2prlgpc41k9'},
  {'name': 'D. Jones',
   'number': 21,
   'position': 'SUB',
   'ssiId': 'c81f45a8-74e2-4e26-98b1-ba8341cbcae1',
   'optaId': '230802',
   'optaUuid': '9n403vt63i8sxmbpu1vp0kcmh'},
  {'name': 'E. Panicco',
   'number': 30,
   'position': 'SUB',
   'ssiId': 'cdd24bdb-d5bf-4d9e-989f-e0fbaf22e7e5',
   'optaId': '500181',
   'optaUuid': '2oo5iizfcb7vdp5jvqd483qsq'},
  {'name': 'D. Lovitz',
   'number': 2,
   'position': 'LB',
   'ssiId': 'df3448b5-1384-43ed-ad52-fba226bc9155',
   'optaId': '177928',
   'optaUuid': '4kflkbicl4vmd7vftq4hdgyqd'},
  {'name': 'D. McCarty',
   'number': 6,
   'position': 'RDM',
   'ssiId': 'eb0ccc58-beaa-44d1-81cc-07df76abaddc',
   'optaId': '41626',
   'optaUuid': '2m4iwb3oo5zzfbxrua7ver3kl'},
  {'name': 'Tah Anunga',
   'number': 27,
   'position': 'SUB',
   'ssiId': 'f9305246-2e96-4771-9125-46d4bf803181',
   'optaId': '243891',
   'optaUuid': '7u1kmvvgmk08p9pawrhxkqwvd'}],
 'awayPlayers': [{'name': 'E. Torres',
   'number': 31,
   'position': 'SUB',
   'ssiId': '0c556d13-981d-4c2f-b3dc-8f5a242a16d8',
   'optaId': '101772',
   'optaUuid': '91lazw34shbdm3qx4soofubit'},
  {'name': 'J. Larentowicz',
   'number': 18,
   'position': 'CDM',
   'ssiId': '0d243058-7e4f-4925-bdd1-a6d34e8ea61b',
   'optaId': '41551',
   'optaUuid': '29yzbetu0kz3siy9prkcesno5'},
  {'name': 'E. Barco',
   'number': 8,
   'position': 'LW',
   'ssiId': '0fdcd073-09bb-4115-a5a9-1ebc3f546f69',
   'optaId': '231969',
   'optaUuid': '9crw9og5xe70mc0m1etggpdk9'},
  {'name': 'F. Escobar',
   'number': 2,
   'position': 'RB',
   'ssiId': '16da8a59-56f9-4244-ad5c-8b6fc8fcce72',
   'optaId': '193891',
   'optaUuid': '5tz98dy8lh2p8a7mq3x9uagnp'},
  {'name': 'A. Walkes',
   'number': 4,
   'position': 'LCB',
   'ssiId': '24532ba5-0072-46ba-8871-872c539e14c3',
   'optaId': '158536',
   'optaUuid': '1qz6h5i13a5tjhrhi3s2sppex'},
  {'name': 'B. Lennon',
   'number': 11,
   'position': 'RW',
   'ssiId': '2927d8a9-bb21-45e0-90de-8551401c8867',
   'optaId': '178386',
   'optaUuid': '234q7lf0bx51r8wehvg51r4k5'},
  {'name': 'B. Guzan',
   'number': 1,
   'position': 'GK',
   'ssiId': '4ecca480-2e0a-46d8-911f-45e5f9b82f8c',
   'optaId': '41705',
   'optaUuid': '26r7731d42flwc6ikxb90jxlh'},
  {'name': 'J. Mulraney',
   'number': 23,
   'position': 'SUB',
   'ssiId': '67d87505-ae47-46ae-b97f-e224ed11b827',
   'optaId': '201651',
   'optaUuid': '92yhyr3ylo3xc31bqvnpbxe51'},
  {'name': 'A. Jahn',
   'number': 14,
   'position': 'ST',
   'ssiId': '84e875bb-8eb3-4dfb-960d-c1d299170231',
   'optaId': '152253',
   'optaUuid': '6k9hinfk6da6yopmrm7jk7b9x'},
  {'name': 'G. Bello',
   'number': 21,
   'position': 'LB',
   'ssiId': '904799ba-19d1-4819-ac67-7e554f1b34b2',
   'optaId': '426771',
   'optaUuid': '61zjhp2dn7uy819kdei4qqqga'},
  {'name': 'T. Wolff',
   'number': 28,
   'position': 'RAM',
   'ssiId': '9058d659-442a-47c7-98d0-f00505bad45f',
   'optaId': '442345',
   'optaUuid': 'ah3swx80hoddr239t1r6qg2ga'},
  {'name': 'A. Kann',
   'number': 25,
   'position': 'SUB',
   'ssiId': '95a73e5b-0246-4512-a3ba-4513d15d87ee',
   'optaId': '156919',
   'optaUuid': 'agjzai69udbed9vhljq5f18lx'},
  {'name': 'Matheus Rossetto',
   'number': 9,
   'position': 'LAM',
   'ssiId': '9cdf5238-f6a4-402b-bb95-ae24ba2de6d2',
   'optaId': '221678',
   'optaUuid': 'cq9z19r30krrf7zule7nh7hex'},
  {'name': 'E. Remedi',
   'number': 5,
   'position': 'SUB',
   'ssiId': 'aeb1e300-1b5d-470a-b90e-19e46955b9c3',
   'optaId': '194102',
   'optaUuid': '4v30smxat71u7nl3x7tgaulzp'},
  {'name': 'M. Robinson',
   'number': 12,
   'position': 'RCB',
   'ssiId': 'b4d3f4aa-34d3-494b-b725-f8dbada1ca81',
   'optaId': '241500',
   'optaUuid': 'bjpjsx12xdi3bwsv35746arqh'},
  {'name': 'E. Hyndman',
   'number': 20,
   'position': 'SUB',
   'ssiId': 'bf0d89e0-989d-42f2-aa29-fc91eeac3a72',
   'optaId': '122342',
   'optaUuid': 'bkyxv0njobtuf80zatjpe53v9'},
  {'name': 'J. Damm',
   'number': 22,
   'position': 'SUB',
   'ssiId': 'c99ef901-93d9-424f-9e7c-5cb111920cbf',
   'optaId': '114060',
   'optaUuid': 'evk0esdocrzt5zxqmv4ostdcl'},
  {'name': 'L. Wyke',
   'number': 27,
   'position': 'SUB',
   'ssiId': 'd50da9ec-af1c-49d2-93aa-9496cb1af80d',
   'optaId': '479575',
   'optaUuid': '2wufroeor0e7k6hvatj1ltwfe'},
  {'name': 'F. Meza',
   'number': 6,
   'position': 'SUB',
   'ssiId': 'dce67827-f6cd-42c2-bd4c-2d3f73a7a1ce',
   'optaId': '57769',
   'optaUuid': '70k0sgj1n6fwi5o10uebx10b9'},
  {'name': 'J. Gallagher',
   'number': 26,
   'position': 'SUB',
   'ssiId': 'fc25bc94-63b2-483f-a3f9-5a2029e31d4e',
   'optaId': '234618',
   'optaUuid': 'ecp53k8d0t7yczah3aebn0yne'}],
 'homeScore': 4,
 'awayScore': 2,
 'ssiId': '886b2a47-3249-4e95-8200-f7cdd8fbbf46',
 'optaId': '2124217',
 'optaUuid': '9hs2nmgkco7hc5inqghgki3h0',
 'homeSsiId': '1eb91611-2625-4f53-9bca-dd074338b933',
 'homeOptaId': '15154',
 'homeOptaUuid': '1oogd0fpwledjm2ycsuv7afze',
 'awaySsiId': 'a060fdd6-3b2a-432c-934d-8ee3a59170c5',
 'awayOptaId': '11091',
 'awayOptaUuid': '943ue6l8ylnidoygbi9p8op2h',
 'venueId': None}

In [41]:
homeplay_df_meta=pd.DataFrame(metadata['homePlayers'])

In [60]:
homeplay_df_meta

,name,number,position,ssiId,optaId,optaUuid
0,A. Danladi,7,RW,0811e82b-9274-4a21-8071-83647b4c4bc9,202195,1wfz5avhq6h41axvxggwa6vvt
1,A. Johnston,12,RB,0c0f65ce-18f4-4f84-862c-29b5d1f9b144,479525,epwfc94g7m7ed1nbt9wbgo6ei
2,T. Washington,23,SUB,12438fbe-f7ac-4aa4-8adb-983bc076fccd,221255,1acejqkxxruued7otxg7wcell
3,A. Godoy,20,LDM,16d1cf1a-1f2c-4802-9616-ce52e351b4dd,99117,4ajhe29nxseyo6wqg3hjdghcl
4,J. Willis,1,GK,1fef9c19-5e91-4e30-a0f5-a92eeca0b927,95309,241n038j8171d06j7y97ug4id
5,D. Romney,4,LCB,2d4e6f77-b4c2-4a77-a903-9fa4b8bff949,213213,49hih9ka1cljgkihamec6b17t
6,A. Winn,19,SUB,39f7d114-a799-472e-ac0b-0151d021df4b,442474,bpkip96s2p3zhx2ew2fl2hwid
7,W. Zimmerman,25,RCB,5998bc4a-77ec-49cc-8736-184bd70d9d6d,151933,eooivgc2bc7bdbl1gq784ehn9
8,J. Maher,18,SUB,68f5a75d-d6d2-41e8-83a4-bc9550716165,421186,a4vlno5u5qsph97hfa71ku8yx
9,A. Muyl,29,LW,779410fe-983c-4e0c-8216-c19b6771878d,220753,64vrzsvixp5cvq9b7ol723zkl
10,D. Badji,9,ST,94c557db-0e5a-422f-ba6a-3ce97322b9f6,202376,dhwk7axf00z4pe7crgp3ge8yx
11,B. Beckeles,55,SUB,a5eba55b-b6ac-471b-9220-4125a541d7f8,99336,akvnlaszzemsj14oa62n39c5x
12,J. Anibaba,3,SUB,a654658a-2189-4a42-8fa3-1c4183eee25c,95228,cfucb8do9rkxdk9381cinmqd
13,H. Mukhtar,10,CAM,ad87de3c-9c65-4623-8a3d-76831d56b038,119089,94jvlb3r2cq9ryxco4fmkbmxh
14,D. Rios,14,SUB,c2951a4d-c534-4b1a-8b3a-b7a078fbf9d8,204328,7su9vrjsmo84ae2prlgpc41k9
15,D. Jones,21,SUB,c81f45a8-74e2-4e26-98b1-ba8341cbcae1,230802,9n403vt63i8sxmbpu1vp0kcmh
16,E. Panicco,30,SUB,cdd24bdb-d5bf-4d9e-989f-e0fbaf22e7e5,500181,2oo5iizfcb7vdp5jvqd483qsq
17,D. Lovitz,2,LB,df3448b5-1384-43ed-ad52-fba226bc9155,177928,4kflkbicl4vmd7vftq4hdgyqd
18,D. McCarty,6,RDM,eb0ccc58-beaa-44d1-81cc-07df76abaddc,41626,2m4iwb3oo5zzfbxrua7ver3kl
19,Tah Anunga,27,SUB,f9305246-2e96-4771-9125-46d4bf803181,243891,7u1kmvvgmk08p9pawrhxkqwvd

In [42]:
awayplay_df_meta=pd.DataFrame(metadata[ 'awayPlayers'])

In [43]:
awayplay_df_meta_sub=awayplay_df_meta.loc[:,['name','number','position','optaId']]

In [36]:
awayplay_df_meta_sub.to_csv("awayplay_df_meta_sub.csv")

In [44]:
press_home_possess

,period,frameIdx,gameClock,wallClock,live,lastTouch,playerIdHome,numberHome,Home_x,Home_y,...,ball_x,ball_y,ball_z,ball_speed,Ball_home_x_squared,Ball_home_y_squared,Ball_home_euclidean,Ball_away_x_squared,Ball_away_y_squared,Ball_away_euclidean
1397,1.0,1397.0,55.88,1.599958e+12,1.0,home,220753,29,-15.68,-25.94,...,-50.41,-0.45,1.00,7.90,1206.1729,649.7401,43.080309,9.1204,0.0729,3.032046
4234,1.0,4234.0,169.36,1.599958e+12,1.0,home,119089,10,-33.39,9.74,...,-19.18,-21.20,3.93,8.52,201.9241,957.2836,34.047139,0.0225,0.0004,0.151327
4245,1.0,4245.0,169.80,1.599958e+12,1.0,home,119089,10,-33.21,9.83,...,-22.80,-22.49,4.44,8.72,108.3681,1044.5824,33.955125,11.9716,2.0736,3.747693
7404,1.0,7404.0,296.16,1.599958e+12,1.0,home,41626,6,-24.86,14.98,...,-34.31,17.86,0.05,5.26,89.3025,8.2944,9.879114,14.9769,5.9536,4.574986
7415,1.0,7415.0,296.60,1.599958e+12,1.0,home,41626,6,-24.91,14.94,...,-37.17,16.62,0.16,7.60,150.3076,2.8224,12.374571,1.0404,1.3456,1.544668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141002,2.0,141002.0,2936.36,1.599964e+12,0.0,home,479525,12,23.70,20.42,...,NaN,NaN,NaN,0.00,561.6900,416.9764,31.283644,5.8081,7.3441,3.626596
141013,2.0,141013.0,2936.80,1.599964e+12,0.0,home,479525,12,23.77,20.51,...,NaN,NaN,NaN,0.00,565.0129,420.6601,31.395430,5.7600,6.6049,3.516376
141024,2.0,141024.0,2937.24,1.599964e+12,0.0,home,479525,12,23.82,20.59,...,NaN,NaN,NaN,0.00,567.3924,423.9481,31.485560,5.7121,5.9049,3.408372
141035,2.0,141035.0,2937.68,1.599964e+12,0.0,home,479525,12,23.88,20.68,...,NaN,NaN,NaN,0.00,570.2544,427.6624,31.589821,5.6644,5.2441,3.302802
141046,2.0,141046.0,2938.12,1.599964e+12,0.0,home,479525,12,23.94,20.76,...,NaN,NaN,NaN,0.00,573.1236,430.9776,31.687556,5.6169,4.6225,3.199906

In [58]:
awayplay_df_meta.loc[:,['name','number','position','optaId']].to_csv('metadata_away.csv')

In [61]:
homeplay_df_meta.loc[:,['name','number','position','optaId']].to_csv('metadata_home.csv')

In [53]:
press_home_df=press_home_possess.loc[:,['period','frameIdx','gameClock','wallClock','playerIdAway','Ball_away_euclidean']]

In [54]:
press_home_df

,period,frameIdx,gameClock,wallClock,playerIdAway,Ball_away_euclidean
1397,1.0,1397.0,55.88,1.599958e+12,41705,3.032046
4234,1.0,4234.0,169.36,1.599958e+12,193891,0.151327
4245,1.0,4245.0,169.80,1.599958e+12,193891,3.747693
7404,1.0,7404.0,296.16,1.599958e+12,221678,4.574986
7415,1.0,7415.0,296.60,1.599958e+12,221678,1.544668
...,...,...,...,...,...,...
141002,2.0,141002.0,2936.36,1.599964e+12,41551,3.626596
141013,2.0,141013.0,2936.80,1.599964e+12,41551,3.516376
141024,2.0,141024.0,2937.24,1.599964e+12,41551,3.408372
141035,2.0,141035.0,2937.68,1.599964e+12,41551,3.302802
141046,2.0,141046.0,2938.12,1.599964e+12,41551,3.199906

In [59]:
press_home_df.to_csv('press_home_data.csv')

In [63]:
press_away_df=press_away_possess.loc[:,['period','frameIdx','gameClock','wallClock','playerIdHome','Ball_away_euclidean']]

In [64]:
press_away_df.to_csv('press_away_data.csv')